### ISSUE TITLE
stuck in TWRP launch screen in chinese varient

### ISSUE THREAD

**Issue by gssdromen** [TwrpBuilder/android_device_xiaomi_violet#2]

**Comment by Dyneteve** [comment]
@gssdromen Use this release for now https://github.com/TwrpBuilder/android_device_xiaomi_violet/releases/tag/TWRP-3.2.3-TwrpBuilder-2019-03-17_18-53

**Comment by Dyneteve** [comment]
also @gssdromen i released a new build witch is suposed to have enc/mtp fixed can you try that too?
